### ISSUE TITLE
Spectabis crashes when I try to Add Game Path

### ISSUE THREAD

**Issue by tegaidogun** [FaithLV/spectabis-next#43]
Spectabis crashes when I try to Add Game Path on my Garuda Linux system with the latest release as of now. I tried building the package using .Net 6.0 and using the official releases but both crashed upon clicking the Add Directory Button.

**Comment by valters-tomsons** [comment]
Hey, thanks for the issue!

Could you please provide log output? https://github.com/valters-tomsons/spectabis-next/blob/master/docs/sharing-logs.md

**Comment by MuskettDev** [comment]
This is the output when running a Spectabis-next built from source code on my machine using Dotnet 6.0 SDK:
```
 otega@CHIBUDOM in repo: spectabis-next/src/SpectabisNext/bin/Debug/net6.0 on  master 
 λ ./SpectabisNext
[ConfigurationManager.cs] Getting default config for 'SpectabisLib.Configuration.UIConfig'
[ConfigurationManager.cs] Loading '/home/otega/.config/spectabis//spectabis.json
[ConfigurationManager.cs] Loading '/home/otega/.config/spectabis//directory.json
[ConfigurationManager.cs] Getting default config for 'SpectabisLib.Configuration.TextConfig'
[PagePreloader.cs] PagePreloader: 774306
[PagePreloader.cs] Preloading page: SpectabisUI.Pages.GameLibrary
[ServiceLib] Creating client to service at 'http://localhost:7071/api/'
[DiscordService.cs] Creating DiscordRPC client
[DiscordService.cs] Updating status to: 'Library'
[PageFactory.cs] Creating new SpectabisUI.Pages.GameLibrary
[PagePreloader.cs] Preloading page: SpectabisUI.Pages.Settings
[PageFactory.cs] Creating new SpectabisUI.Pages.Settings
[PagePreloader.cs] Preloading page: SpectabisUI.Pages.CreateProfile
[LocalDatabaseProvider.cs] Building game database
[LocalDatabaseProvider.cs] GameDatabaseProvider: Reading PCSX2 game database from 'Resources/gamedatabase.csv'
[LocalDatabaseProvider.cs] Building game index
[PageFactory.cs] Creating new SpectabisUI.Pages.CreateProfile
[PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.GameLibrary
[PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.Settings
[PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.CreateProfile
[Program.cs] Starting Spectabis 'develop'
Unhandled exception. System.InvalidOperationException: Cannot show window with non-visible parent.
   at Avalonia.Controls.Window.ShowDialog[TResult](Window owner) in /_/src/Avalonia.Controls/Window.cs:line 750
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.Show(SystemDialog d, Window parent, ManagedFileDialogOptions options) in /_/src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs:line 36
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.ShowFolderDialogAsync(OpenFolderDialog dialog, Window parent) in /_/src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs:line 47
   at SpectabisNext.Services.FileBrowser.BeginGetDirectoryPath(String title, String path) in /home/otega/spectabis-next/src/SpectabisNext/Services/FileBrowser.cs:line 28
   at SpectabisUI.Pages.Settings.AddScanClick(Object sender, RoutedEventArgs e) in /home/otega/spectabis-next/src/SpectabisUI/Pages/Settings.xaml.cs:line 70
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 57
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 46
   at SpectabisNext.Spectabis.Start() in /home/otega/spectabis-next/src/SpectabisNext/Spectabis.cs:line 21
   at SpectabisNext.Program.StartSpectabis(IContainer container, String[] arguments) in /home/otega/spectabis-next/src/SpectabisNext/Program.cs:line 38
   at SpectabisNext.Program.Main(String[] args) in /home/otega/spectabis-next/src/SpectabisNext/Program.cs:line 15
   at SpectabisNext.Program.<Main>(String[] args)
fish: Job 1, './SpectabisNext' terminated by signal SIGABRT (Abort)

```

**Comment by MuskettDev** [comment]
Is it a problem with Avalonia?

**Comment by valters-tomsons** [comment]
Can reproduce after updating Avalonia, so I must've broken this at some point. Will investigate. :+1:

**Comment by valters-tomsons** [comment]
Fixed with https://github.com/valters-tomsons/spectabis-next/commit/ae217dfff350a6b3ad7e9a9e6ed4746e39588909, but don't bother. Game scanning itself is not implemented _yet_
